# Generated by Django 3.1.4 on 2021-01-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTodoWooFlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
                ('memo_box', models.TextField()),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_email', models.EmailField(max_length=250)),
                ('memo_created_date', models.DateTimeField(auto_now_add=True)),
                ('memo_complete_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
