# Generated by Django 3.1.4 on 2021-01-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodowooflo',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projecttodowooflo',
            name='memo_box',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttodowooflo',
            name='memo_complete_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttodowooflo',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
