# Generated by Django 3.1.4 on 2021-01-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210118_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodowooflo',
            name='image',
            field=models.ImageField(upload_to='todo/images/'),
        ),
        migrations.AlterField(
            model_name='projecttodowooflo',
            name='memo_complete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
