# Generated by Django 3.1.4 on 2021-01-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210124_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttodowooflo',
            old_name='user',
            new_name='user_name',
        ),
    ]
