# Generated by Django 3.1.4 on 2021-01-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210124_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttodowooflo',
            old_name='usercreator',
            new_name='user_name',
        ),
    ]
