# Generated by Django 3.1.4 on 2020-12-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFlo',
            new_name='Project',
        ),
    ]
