# Generated by Django 3.1.4 on 2020-12-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201229_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectFlo',
        ),
    ]
